version: '3.7'

services:
  db:
    image: postgres:12-alpine
    ports:
      - "${DATABASE_EXPOSE_PORT}:${DATABASE_PORT}"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    command: -p ${DATABASE_PORT}

  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    depends_on:
      - db
    working_dir: /usr/src/app  # Указываем рабочую директорию
    command: >
      sh -c "
      npm run migration:run &&
      npm run start:dev"
volumes:
  postgres_data: {}