const USER = {
    FORM: 'SUCCESS_FORM',
    SUCCESS_LOGIN: 'SUCCESS_LOGIN',
    DELETE: 'SUCCESS_DELETE',
    UPDATE: 'SUCCESS_UPDATE',
    PASSWORD_CHANGED: 'SUCCESS_PASSWORD_CHANGED',
};
  
export const SUCCESS = {
    USER,
};
  