enum USER {
    NOT_FOUND = 'ERR_USER_NOT_FOUND',
    EMAIL_EXISTS = 'ERR_USER_EMAIL_EXISTS',
    PHONE_EXISTS = 'ERR_USER_PHONE_EXISTS',
    INCORRECT_LOGIN_OR_PASSWORD = 'ERR_INCORRECT_LOGIN_OR_PASSWORD',
    PASSWORD_MISMATCH = 'ERR_PASSWORD_MISMATCH',
    INCORRECT_PASSWORD = 'ERR_INCORRECT_PASSWORD',
}
  
export const ERR = {
    USER,
};
